### ISSUE TITLE
How do you know the current connection state

### ISSUE THREAD

**Issue by udofly** [SammyVimes/ACentrifugo#20]
How do you know the current connection state, for example, the current connection is broken.How can I judge? Thank you very much！

**Comment by FZambia** [comment]
Hello! This library is not maintained anymore as its maintainer just gone... I can only suggest you to take a look at Centrifugo v2 and its actual list of supported libraries: https://centrifugal.github.io/centrifugo/libraries/client/

**Comment by udofly** [comment]
Thank you very much, I will update sometime
